-- apply changes
create table players (
  id                            bigint generated by default as identity not null,
  uuid                          uuid not null,
  verified                      boolean default false not null,
  discord_id                    varchar(255) not null,
  verification_message_id       varchar(255),
  constraint uq_players_uuid unique (uuid),
  constraint uq_players_discord_id unique (discord_id),
  constraint pk_players primary key (id)
);
comment on column players.uuid is 'Mojang assigned UUID';
comment on column players.verified is 'Weather the user has verified their discord account linkage';
comment on column players.discord_id is 'Discord snowflake ID';
comment on column players.verification_message_id is 'ID of the discord message sent during verification';

