-- apply changes
create table players (
  id                            bigint generated by default as identity not null,
  uuid                          uuid not null,
  verified                      boolean default false not null,
  discord_id                    varchar(255) not null,
  constraint uq_players_uuid unique (uuid),
  constraint uq_players_discord_id unique (discord_id),
  constraint pk_players primary key (id)
);
comment on column players.uuid is 'Mojang assigned UUID';
comment on column players.verified is 'Whether the user has verified their discord account linkage';
comment on column players.discord_id is 'Discord snowflake ID';

create table verifications (
  id                            bigint generated by default as identity not null,
  player_id                     bigint not null,
  type                          varchar(16),
  value                         varchar(255),
  constraint ck_verifications_type check ( type in ('message_reaction','code')),
  constraint uq_verifications_player_id unique (player_id),
  constraint uq_verifications_value unique (value),
  constraint pk_verifications primary key (id)
);
comment on column verifications.type is 'Type of verification';
comment on column verifications.value is 'Value of the verification, this is a messageId in message_reaction and a code in code';

alter table verifications add constraint fk_verifications_player_id foreign key (player_id) references players (id) on delete cascade on update restrict;

