discord:
  token:
  server_id:
  owner_id:

# Database settings, this specifies where your data is stored
database:
  # The method of storing data, the database type
  # - Possible options:
  #   | Remote databases - require connection information to be configured below
  #   | => MySQL
  #   | => PostgreSQL
  #
  #   | Flat file/local database - don't require any extra configuration
  #   | => SQLite
  #   | => H2
  method: h2

  # These options are only used if you use Remote databases
  # If you use flat file then these options do not matter
  connection-options:
    # Define the address and port for the database.
    # - The standard DB engine port is used by default
    #   (MySQL: 3306, PostgreSQL: 5432)
    # - Specify as "host:port" if differs
    address: localhost

    # Name of the database to use
    name: discordlink

    # Credentials for the database.
    username: root
    password: ''

link:
  # Requires link to play on the server
  required: false

  # Should the player respawn at the world spawn after verification. This setting will only be used if link.required is true
  verify_spawn: false

  # Allow unlinking your minecraft account from discord
  allow_unlink: true

# Should chat be controlled by this plugin
chat:
  enabled: true

  # This format will only show in game depending on where the message came from
  # Unlinked format only required if link.required is set to false
  #
  # Variables:
  #   %username% - Minecraft username
  #   %message% - Message contents
  #
  # Linked Only Variables:
  #   %color% - Top role color
  #   %tag% - Discord Tag
  format:
    # Message formats for player messages
    player:
      # Should chat format should be applied on regular messages?
      enabled: true

      linked: '<gray>[<dark_green>MC<gray>] %color%%username% <gray>(<italic>%tag%</italic>) » <reset>%message%'
      unlinked: '<gray>[<dark_green>MC<gray>] %username% » <reset>%message%'

    # Message formats for discord messages
    # This will never show if chat.crosschat is disabled
    # This does not have an enabled field as there is nothing else to process chat messages from discord
    discord:
      linked: '<gray>[<blue>Discord<gray>] %color%%username% <gray>(<italic>%tag%</italic>) » <reset>%message%'
      unlinked: '<gray>[<blue>Discord<gray>] %color%%tag% <gray>» <reset>%message%'

  # This will allow minecraft and discord chats/events to communicate with each other in a single channel
  crosschat:
    enabled: true

    # Which events should be broadcast to the channel
    events:
      join: true
      quit: true
      death: true

    # This channel ID must be in the specified server_id server
    channel_id:

    # This webhook CAN be a different channel than channel_id but SHOULDN'T
    # If it is different messages will not be relayed in the same place
    webhook:

# Hijack and control player status messages
# If enabled these messages won't be sent until the user has linked their account
# Unlinked format only required if link.required is set to false
# tag and color variables are only valid in linked messages
#
# Variables:
#   %username% - Minecraft username
#
# Linked Only Variables:
#   %color% - Top role color
#   %tag% - Discord Tag
status_messages:
  enabled: true
  join:
    linked: '%color%%username% <gray>(<italic>%tag%</italic>) joined the game'
    unlinked: '<gray>%username% joined the game'

  quit:
    linked: '%color%%username% <gray>(<italic>%tag%</italic>) left the game'
    unlinked: '<gray>%username% left the game'

  # Variables:
  #   %cause% - Cause of death in game
  death:
    linked: '%color%%username% <gray>(<italic>%tag%</italic>) %cause%'
    unlinked: '<gray>%username% %cause%'

kick_messages:
  # Only happens if player is linked, link.allow_unlink is false, and player leaves the guild
  not_in_guild: |-
    <red>You must be a member of the discord server to play on this Minecraft server
    <red>Your Minecraft account is already linked to <yellow>%tag%
    <gray><italic>discord.gg/invite
  # When user is linked and gets banned from discord
  # In the future this will be an actual ban listener and not a kick and can be disabled
  banned: |-
    <red>You have been banned from the discord server
    <gray><italic>discord.gg/invite
  # If the account was ToS banned or deleted
  # This assumes that you did something bad and shouldn't be able to play
  # In the future this will be an actual listener and not a kick and can be disabled
  tos: |-
    <red>Your account is ToS banned or deleted
    <gray><italic>discord.gg/invite